### ISSUE TITLE
PlatformIO

### ISSUE THREAD

**Issue by jhd-old** [m5stack/M5Unit-KMeterISO#1]
Will this library also be added to PlatformIO? 
Currently there is only M5Unit-KMeter.

**Comment by Gitshaoxiang** [comment]
yes. for the time being . you could clone it to the PIO project "lib" path directly

![image](https://github.com/m5stack/M5Unit-KMeterISO/assets/45260108/5ea70e2a-89b8-4252-9984-ee1015af4438)
